### PR TITLE
Deeper cleanup

### PR DESCRIPTION
**Pull request by Cabalist**
This is a much more aggressive cleanup of the code base than the original.  I'm aware that it is bad form to submit such a huge pull request but I've tried to make it segmented for easier reviewing.

This is best looked at on a commit by commit level.  Each commit is localized to one file and summarizes the changes that happened.    I have uncovered a few issues and have marked them with todos.   There are larger refactors that could happen but I would like a deeper understanding of the code before I pursue them.  All code is Python 2.6 compliant. 

I would like to add in Python3 compatibility for that inevitability and break out the duplicated code into some helper functions.  Breaking the code into smaller functions would also allow for tests being more easily written.  

To view this diff with whitespace ignored just add ?w=1 to the end of the url. Like this: `https://github.com/evil-mad/EggBot/pull/97/files?w=1`

### CODE REVIEW

**Comment by Cabalist** [comment]
Also!  This library is ripe for places to use mypy typing.  That is also on my todo list.  :)

**Comment by Cabalist** [comment]
Cool.  Thanks for taking the time to review this!  I 100% agree that future pull requests should be smaller.  I started down a path and it kind of snowballed...  I can split this one up into smaller ones if that would make this nicer.  

I'll try and address feedback below:
> I do not follow how this is renaming "local varaibles for PEP8" -- PEP8 does not require migration from camelcase to underscores.

I was going off of [this section in PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) which states that Functions and Variables should be *'lowercase, with words separated by underscores as necessary to improve readability'* I did not change function names because that would cause breaking API changes for applications using these as a library.  CamelCase is reserved for class declaration i.e.  `class EggBot(object): ...` 

This (like spaces) can be a rough transition on an existing codebase but IMHO makes the code a lot more readable.  PEP8 is a recommendation not a rule but I do think this is a worthwhile change.

>Looks like this commit broke eggbot_acrostic.py as well; reverting to eval allows it to work again. It's not clear to me how getattr is appropriate for parsing the option variables.  

Yep.  That line should be 
`line = getattr(self.options, 'line{0}'.format(i)).strip()`  instead of `line = getattr(self.options.line, str(i)).strip()`  Fix shortly.

> So far as I know, range requires a starting value if you need to use the step argument. eggbot_maze is broken in pull request, can be repaired with for x in range(0,self.w,2):

ouch.  That was dumb.  Yep! I'll add back in the `start`.

> To fix the crash, suggest change of:
self.mapPathVertices(d, node, mat_new, find_bbox) # TODO This will crash Wrong call arguments -> self.getPathVertices(d, node, mat_new, find_bbox)

Will do.

>in inkex.addNS('circle', 'svg'), node.tag == 'circle'] the node.tag == should be removed.

Will do.

> This commit breaks the proper rendering of the font table. Reverting one line to
letter_vals = [ord(q) - 32 for q in (f[1] + ' -> ')] seems to fix it.

Interesting.  I must have missed where letter_vals is used later on.  Which line did you revert?  

> This diff is hard to read... (We need to make the variable names shorter, not longer.) 

The code for eggbot_hatch.py was very strange.  There was a great deal of copy and paste and commented out code.  There also were a few places where the code just kind of trailed off declaring variables and calling things but never returning.  It is a good candidate for some tests and refactors.

I conditionally agree on the shorter variables names.  I'm a big believer in descriptive variable names but some of these when converted to snake_case got HUGE.  I believe that some variable names have some typing incorporated into them (i.e. f_blah or pnt_blah) and that can be trimmed off when types get added in.  The huge ones can always be renamed.

**Comment by Cabalist** [comment]
>This commit breaks the proper rendering of the font table. Reverting one line to
letter_vals = [ord(q) - 32 for q in (f[1] + ' -> ')] seems to fix it.

I should have read that closer.  I see the issue.  The generator is/was trying to be consumed twice.  The fixes you pointed out have been added.

**Comment by oskay** [comment]
Merged -- thank you!

**Pull request merged**
