### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Cabalist**
Hey there,

We've been playing with our eggbot a lot recently.  I decided to check out some code and did some general cleanup while I was reading through.  

After applying some PEP8 rules to calm down my linter I started to notice some larger issues .  There are some places the code will crash every time or mutable default arguments are applied.  I'm interested in fixing these but felt like this made a big enough pull request as it was.

There should be no functional changes to the code.

PEP8
Make consistent whitespace ( Change a mix of tabs/spaces -> tabs)  [I prefer spaces when possible... 
 😬 ]
Prevent name space clobbering i.e. (from blah import *)
sort imports and removed unused
replace `dict.has_key(key)` with `key in dict` .  `.has_key()` has been depreciated for some time.
Add file encoding
Remove unnecessary semicolons  

To view this diff with whitespace ignore just add `?w=1` to the end of the url.  Like this:  `https://github.com/evil-mad/EggBot/pull/96/files?w=1`

### CODE REVIEW

**Comment by oskay** [comment]
Thank you for doing this!

I agree with the changes in general, but I'd like to review this a bit before committing. 

To the extent that there are "no functional changes", I'm happy to have help with these kinds of cleanup issues. 

I can see that eggbot_acrostic.py has been broken by removing the line `import hersheydata`.  Please fix this one. (I can't help wondering if there are other "functional" changes that I'm not noticing.)

The typo correction is most welcome. (I've never really looked at the source code of a few of these less-used components.)

I'm unable to test the python-eagle code; it is an old, seldom-used demo fork. Perhaps it should be pruned from the repository.

**Comment by Cabalist** [comment]
Hey there,

Absolutely!  This is a huge changeset and I apologize for that.   I missed the `eval`s  in eggbot_acrostic.py.  I looked through the rest of python code and the hersheydata is not omitted on the other ones and evals don't address any other objects (except one `self` in eggbot_acrostic).  These eval lines could be replaced by getattr() calls to prevent confusion and increase security.  

Something like:

```font = eval('hersheydata.' + str(self.options.fontface))```

to 

``` font = gettattr(hersheydata,  str(self.options.fontface))```

**Comment by Cabalist** [comment]
Also I noticed this in the code:

```        # Cater to Python 2.4 and earlier ```

Is this still true?  What is the minimal version of Python you'd like to support?

**Comment by oskay** [comment]
We still (unfortunately) need to support back to python 2.6.

**Comment by Cabalist** [comment]
That's fine.  Out of curiosity who is still Python2.6?  Is inkscape still bundling that version?

**Comment by oskay** [comment]
We're still supporting Inkscape 0.91, which uses python 2.6 on Windows. Inkscape 0.92 has only been out on all platforms for a few months, and our extensions don't fully support it yet. (We'll  be there soon.)

**Comment by Cabalist** [comment]
That makes sense!  Thanks for clarifying.  :)

**Comment by oskay** [comment]
Merged; thank you again!

**Pull request merged**
